:green_heart: Fix CI failures from unparseable Makefile
i.e.,
```
Run make provision-environment
  make provision-environment
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.5/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.5/x64/lib
Makefile:153: *** missing separator.  Stop.
Error: Process completed with exit code 2.
```

Runs fine locally with same shell and flag, expediently fixing error by
marking template as a comment. We must live with an extraneous hash
symbol.