:construction_worker: Test across all supported platforms
Note: Windows-incompatible due to `nodeenv` dependency required by
Log4Brains ADR management library; if this dependency is removed, may
work for Windows.

Example error log:
```
Run make provision-environment
poetry update --lock -v
Creating virtualenv cookiecutter-cruft-poetry-tox-pre-commit-ci-cd-instance in D:\a\cookiecutter-cruft-poetry-tox-pre-commit-ci-cd-instance\cookiecutter-cruft-poetry-tox-pre-commit-ci-cd-instance\.venv
Using virtualenv: D:\a\cookiecutter-cruft-poetry-tox-pre-commit-ci-cd-instance\cookiecutter-cruft-poetry-tox-pre-commit-ci-cd-instance\.venv
Updating dependencies
Resolving dependencies...
```
...
```
poetry install --extras docs -v
Using virtualenv: D:\a\cookiecutter-cruft-poetry-tox-pre-commit-ci-cd-instance\cookiecutter-cruft-poetry-tox-pre-commit-ci-cd-instance\.venv
Installing dependencies from lock file

Finding the necessary packages for the current system

Package operations: 184 installs, 0 updates, 0 removals, 3 skipped

  � Removing appnope (0.1.2): Skipped for the following reason: Not currently installed
  � Removing pexpect (4.8.0): Skipped for the following reason: Not currently installed
  � Removing ptyprocess (0.7.0): Skipped for the following reason: Not currently installed
  � Installing ipython-genutils (0.2.0)
  � Installing zipp (3.5.0)
  � Installing attrs (21.2.0)
  � Installing importlib-metadata (2.1.1)
  � Installing pyrsistent (0.18.0)
  � Installing six (1.16.0)
  � Installing traitlets (5.0.5)
  � Installing pywin32 (301)
  � Installing jsonschema (3.2.0)
  � Installing jupyter-core (4.7.1)
  � Installing nest-asyncio (1.5.1)
  � Installing pyparsing (2.4.7)
  � Installing python-dateutil (2.8.2)
  � Installing parso (0.8.2)
  � Installing pyzmq (22.2.1)
  � Installing tornado (6.1)
  � Installing wcwidth (0.2.5)
  � Installing async-generator (1.10)
  � Installing backcall (0.2.0)
  � Installing colorama (0.4.4)
  � Installing decorator (5.0.9)
  � Installing jupyter-client (6.2.0)
  � Installing jedi (0.18.0)
  � Installing markupsafe (2.0.1)
  � Installing matplotlib-inline (0.1.2)
  � Installing nbformat (5.1.3)
  � Installing packaging (21.0)
  � Installing pickleshare (0.7.5)
  � Installing prompt-toolkit (3.0.19)
  � Installing pycparser (2.20)
  � Installing pygments (2.9.0)
  � Installing webencodings (0.5.1)
  � Installing bleach (4.0.0)
  � Installing cffi (1.14.6)
  � Installing debugpy (1.4.1)
  � Installing entrypoints (0.3)
  � Installing ipython (7.26.0)
  � Installing defusedxml (0.7.1)
  � Installing jinja2 (3.0.1)
  � Installing jupyterlab-pygments (0.1.2)
  � Installing mistune (0.8.4)
  � Installing nbclient (0.5.3)
  � Installing pandocfilters (1.4.3)
  � Installing pywinpty (1.1.3)
  � Installing testpath (0.5.0)
  � Installing argon2-cffi (20.1.0)
  � Installing ipykernel (6.0.3)
  � Installing nbconvert (6.1.0)
  � Installing send2trash (1.7.1)
  � Installing terminado (0.10.1)
  � Installing prometheus-client (0.11.0)
  � Installing typing-extensions (3.10.0.0)
  � Installing arrow (1.1.1)
  � Installing atomicwrites (1.4.0)
  � Installing backports.entry-points-selectable (1.1.0)
  � Installing chardet (4.0.0)
  � Installing charset-normalizer (2.0.4)
  � Installing certifi (2021.5.30)
  � Installing distlib (0.3.2)
  � Installing filelock (3.0.12)
  � Installing idna (3.2)
  � Installing iniconfig (1.1.1)
  � Installing notebook (6.4.2)
  � Installing platformdirs (2.2.0)
  � Installing pluggy (0.13.1)
  � Installing py (1.10.0)
  � Installing pytz (2021.1)
  � Installing smmap (4.0.0)
  � Installing text-unidecode (1.3)
  � Installing toml (0.10.2)
  � Installing urllib3 (1.26.6)
  � Installing alabaster (0.7.12)
  � Installing asttokens (2.0.5)
  � Installing babel (2.9.1)
  � Installing binaryornot (0.4.4)
  � Installing coverage (6.0b1)
  � Installing click (7.1.2)
  � Installing distro (1.6.0)
  � Installing docutils (0.16)
  � Installing gitdb (4.0.7)
  � Installing imagesize (1.2.0)
  � Installing jinja2-time (0.2.0)
  � Installing jupyterlab-widgets (1.0.0)
  � Installing lazy-object-proxy (1.6.0)
  � Installing markdown-it-py (1.1.0)
  � Installing mccabe (0.6.1)
  � Installing poyo (0.5.0)
  � Installing pycodestyle (2.7.0)
  � Installing pyflakes (2.3.1)
  � Installing pytest (6.2.4)
  � Installing python-slugify (5.0.2)
  � Installing qtpy (1.9.0)
  � Installing requests (2.26.0)
  � Installing sentry-sdk (1.3.1)
  � Installing snowballstemmer (2.1.0)
  � Installing sortedcontainers (2.4.0)
  � Installing sphinxcontrib-applehelp (1.0.2)
  � Installing sphinxcontrib-devhelp (1.0.2)
  � Installing sphinxcontrib-htmlhelp (2.0.0)
  � Installing sphinxcontrib-jsmath (1.0.1)
  � Installing sphinxcontrib-qthelp (1.0.3)
  � Installing sphinxcontrib-serializinghtml (1.1.5)
  � Installing typed-ast (1.4.3)
  � Installing virtualenv (20.7.0)
  � Installing widgetsnbextension (3.5.1)
  � Installing wrapt (1.12.1)
  � Installing appdirs (1.4.4)
  � Installing astroid (2.6.6)
  � Installing cfgv (3.3.0)
  � Installing codecov (2.1.12)
  � Installing cookiecutter (1.7.3)
  � Installing cmake (3.21.1.post1)
  � Installing cycler (0.10.0)
  � Installing execnet (1.9.0)
  � Installing flake8 (3.9.2)
  � Installing future (0.18.2)
  � Installing gitpython (3.1.20)
  � Installing glob2 (0.7)
  � Installing hypothesis (6.14.5)
  � Installing icontract (2.5.3)
  � Installing identify (2.2.13)
  � Installing ipywidgets (7.6.3)
  � Installing isort (5.9.3)
  � Installing junit-xml (1.8)
  � Installing jupyter-console (6.4.0)
  � Installing kiwisolver (1.3.1)
  � Installing mdit-py-plugins (0.2.8)
  � Installing mypy-extensions (0.4.3)
  � Installing ninja (1.10.2)
  � Installing nodeenv (1.6.0)
  � Installing numpy (1.21.1)
  � Installing orjson (3.6.1)
  � Installing pathspec (0.9.0)
  � Installing pillow (8.3.1)
  � Installing pony (0.7.14)
  � Installing py-cpuinfo (8.0.0)
  � Installing pybind11 (2.7.1)
  � Installing pygal (2.4.0)
  � Installing pygaljs (1.0.2)
  � Installing pytest-cov (2.12.1)
  � Installing pytest-forked (1.3.0)
  � Installing python-dotenv (0.18.0)
  � Installing pyyaml (5.4.1)
  � Installing qtconsole (5.1.1)
  � Installing regex (2021.8.3)
  � Installing scikit-build (0.11.1)
  � Installing shellingham (1.4.0)
  � Installing sphinx (4.1.2)
  � Installing structlog (21.1.0)
  � Installing structlog-sentry (1.4.0)
  � Installing termcolor (1.1.0)
  � Installing tokenize-rt (4.1.0)
  � Installing tomli (1.2.1)
  � Installing tox (3.24.1)
  � Installing typer (0.3.2)
  � Installing unidecode (1.2.0)
  � Installing black (21.7b0)
  � Installing cruft (2.9.0)
  � Installing darglint (1.8.0)
  � Installing emoji (1.4.2)
  � Installing flakehell (0.9.0)
  � Installing icontract-hypothesis (1.1.7)
  � Installing jupyter (1.0.0)
  � Installing matplotlib (3.4.2)
  � Installing mutmut (2.2.0)
  � Installing mypy (0.910)
  � Installing myst-parser (0.15.1)
  � Installing nbqa (0.13.1)
  � Installing pre-commit (2.14.0)
  � Installing pylint (2.9.6)
  � Installing pytest-benchmark (3.4.1)
  � Installing pytest-emoji (0.2.0)
  � Installing pytest-mock (3.6.1)
  � Installing pytest-sugar (0.9.4)
  � Installing pytest-xdist (2.3.0)
  � Installing sphinx-autoapi (1.8.3)
  � Installing sphinx-rtd-theme (0.5.2)
  � Installing sphinxcontrib-confluencebuilder (1.5.0)
  � Installing structlog-sentry-logger (0.8.2)
  � Installing tox-gh-actions (2.6.0)
  � Installing typeguard (2.12.1)
  � Installing typer-cli (0.0.11)
  � Installing types-emoji (1.2.2)
  � Installing xdoctest (0.15.5)

Installing the current project: cookiecutter-cruft-poetry-tox-pre-commit-ci-cd-instance (0.0.0)
# Install node ADR management library
poetry run nodeenv --python-virtualenv --jobs=8
Usage: nodeenv [OPTIONS] ENV_DIR

nodeenv: error: no such option: --jobs
mingw32-make: *** [Makefile:124: provision-environment] Error 2
Error: Process completed with exit code 1.
```